version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: booking
      MYSQL_USER: root
      MYSQL_PASSWORD: 1mde
      MYSQL_ROOT_PASSWORD: 1-qwerty
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  web:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata datadump.json &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DB_NAME=booking
      - DB_USER=root
      - DB_PASSWORD=1-qwerty
      - DB_HOST=db
      - DB_PORT=3306

volumes:
  mysql_data:
